### ISSUE TITLE
Distributed package doesn't have NCCL built in

### ISSUE THREAD

**Issue by betterftr** [bshall/hubert#1]
Traceback (most recent call last):
  File "E:\VC\hubert\train.py", line 448, in <module>
    mp.spawn(
  File "H:\CONDA\envs\stylegan3\lib\site-packages\torch\multiprocessing\spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "H:\CONDA\envs\stylegan3\lib\site-packages\torch\multiprocessing\spawn.py", line 198, in start_processes
    while not context.join():
  File "H:\CONDA\envs\stylegan3\lib\site-packages\torch\multiprocessing\spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "H:\CONDA\envs\stylegan3\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "E:\VC\hubert\train.py", line 44, in train
    dist.init_process_group(
  File "H:\CONDA\envs\stylegan3\lib\site-packages\torch\distributed\distributed_c10d.py", line 602, in init_process_group
    default_pg = _new_process_group_helper(
  File "H:\CONDA\envs\stylegan3\lib\site-packages\torch\distributed\distributed_c10d.py", line 727, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL " "built in")
RuntimeError: Distributed package doesn't have NCCL built in

**Comment by bshall** [comment]
Hi @betterftr, if your system doesn't have the NCCL backend available you'll have to configure the training script to either use MPI or GLOO (see [here](https://pytorch.org/docs/stable/distributed.html) for details).
