### ISSUE TITLE
Error trying to fine tuning the model

### ISSUE THREAD

**Issue by mathigatti** [bshall/hubert#2]
Hi! Thanks for sharing this project, it's amazing.

I'm trying to run `!python train.py --resume /content/hubert-soft.pt --mask /content/wavs/ /content/`

Using the checkpoint of hubert-soft you [released](https://github.com/bshall/hubert/releases), but I got `KeyError: 'hubert'`, it looks like the code is looking for more than just the hubert-soft model, the [load_checkpoint](https://github.com/bshall/hubert/blob/main/hubert/utils.py#L55) function seems to look for hubert, its scaler and optimizer, do I need checkpoints for that too?

On the other hand, do you know if training it on a dataset containing speech + singing might help to make it better at singing voice conversion? It tried soft-vc and the quality is pretty good but it pretty much ignores the pitch/notes when trying to sing. I'm thinking if it might be better to fine tune hubert or maybe adding extra pitch information to the input of tacotron2.

```python
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
INFO:numexpr.utils:NumExpr defaulting to 2 threads.
/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:566: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
INFO:__mp_main__:Loading checkpoint from /content/hubert-soft.pt
Traceback (most recent call last):
  File "train.py", line 452, in <module>
    join=True,
  File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/content/hubert/train.py", line 143, in train
    logger=logger,
  File "/content/hubert/hubert/utils.py", line 55, in load_checkpoint
    hubert.load_state_dict(checkpoint["hubert"])
KeyError: 'hubert'
```

**Comment by hamidreza-asjodi** [comment]
same problem
